spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
      schema-locations: classpath:schema.sql
     # data-locations: classpath:demo_data.sql


security:
  jwt:
    secret: aGZiYmtiYWllYmNpZWFpZWJsZWNldWNlY2xhZWNhaWJlbGNhZWN3Q0VCV0VXSUM=
    access: 3600000
    refresh: 2592000000